In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df=pd.read_csv("fifa_ranking_2022-10-06.csv")
df.head(10)

,team,team_code,association,rank,previous_rank,points,previous_points
0,Brazil,BRA,CONMEBOL,1,1,1841.30,1837.56
1,Belgium,BEL,UEFA,2,2,1816.71,1821.92
2,Argentina,ARG,CONMEBOL,3,3,1773.88,1770.65
3,France,FRA,UEFA,4,4,1759.78,1764.85
4,England,ENG,UEFA,5,5,1728.47,1737.46
5,Italy,ITA,UEFA,6,7,1726.14,1713.86
6,Spain,ESP,UEFA,7,6,1715.22,1716.93
7,Netherlands,NED,UEFA,8,8,1694.51,1679.41
8,Portugal,POR,UEFA,9,9,1676.56,1678.65
9,Denmark,DEN,UEFA,10,10,1666.57,1665.47

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team             211 non-null    object
 1   team_code        211 non-null    object
 2   association      211 non-null    object
 3   rank             211 non-null    int64
 4   previous_rank    211 non-null    int64
 5   points           211 non-null    float64
 6   previous_points  211 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 11.7+ KB

In [6]:
df.describe()

            rank  previous_rank       points  previous_points
count  211.00000      211.00000   211.000000       211.000000
mean   106.00000      106.00000  1220.687346      1220.645592
std     61.05462       61.05462   253.420954       253.331712
min      1.00000        1.00000   762.220000       763.820000
25%     53.50000       53.50000  1007.675000      1008.330000
50%    106.00000      106.00000  1192.090000      1183.900000
75%    158.50000      158.50000  1433.465000      1431.790000
max    211.00000      211.00000  1841.300000      1837.560000

In [8]:
df.shape

(211, 7)

In [9]:
df.columns

Index(['team', 'team_code', 'association', 'rank', 'previous_rank', 'points',
       'previous_points'],
      dtype='object')

In [10]:
df.duplicated().sum()

np.int64(0)