In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("matches_1930_2022.csv")
df.head(10)

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...
5,England,France,1,2.4,NaN,2,0.9,NaN,Gareth Southgate,Harry Kane,...,NaN,NaN,NaN,NaN,NaN,NaN,['90&rsquor;|1:2|Harry Maguire'],"['43&rsquor;|0:1|Antoine Griezmann', '47&rsquo...",['79&rsquor;|1:2|Raheem Sterling|for Bukayo Sa...,['79&rsquor;|1:2|Kingsley Coman|for Ousmane De...
6,Croatia,Brazil,1,0.6,4.0,1,2.5,2.0,Zlatko Dalić,Luka Modrić,...,NaN,"['2|1:0|Rodrygo', '8|4:2|Marquinhos']",NaN,NaN,NaN,NaN,"['31&rsquor;|0:0|Marcelo Brozović', '117&rsquo...","['25&rsquor;|0:0|Danilo', '68&rsquor;|0:0|Case...",['72&rsquor;|0:0|Nikola Vlašić|for Mario Pašal...,"['56&rsquor;|0:0|Antony|for Raphinha', '64&rsq..."
7,Netherlands,Argentina,2,0.6,3.0,2,1.9,4.0,Louis van Gaal,Virgil van Dijk,...,"['1|0:0|Virgil van Dijk', '3|0:1|Steven Berghu...",['8|2:3|Enzo Fernández'],NaN,NaN,Denzel Dumfries · 120+3,NaN,"['43&rsquor;|0:1|Jurriën Timber', '45+2&rsquor...","['31&rsquor;|0:0|Walter Samuel', '43&rsquor;|0...",['46&rsquor;|0:1|Steven Berghuis|for Steven Be...,['66&rsquor;|0:1|Leandro Paredes|for Rodrigo D...
8,Morocco,Spain,0,0.7,3.0,0,1.0,0.0,Hoalid Regragui,Romain Saïss,...,['5|2:0|Badr Banoun'],"['2|1:0|Pablo Sarabia', '4|2:0|Carlos Soler', ...",NaN,NaN,NaN,NaN,['90&rsquor;|0:0|Romain Saïss'],['77&rsquor;|0:0|Aymeric Laporte'],['66&rsquor;|0:0|Abdessamad Ezzalzouli|for Sof...,['63&rsquor;|0:0|Álvaro Morata|for Marco Asens...
9,Portugal,Switzerland,6,2.3,NaN,1,1.2,NaN,Fernando Santos,Pepe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['43&rsquor;|2:0|Fabian Schär', '59&rsquor;|4:...",['73&rsquor;|5:1|Cristiano Ronaldo|for Gonçalo...,['46&rsquor;|2:0|Eray Cömert|for Fabian Schär'...

In [4]:
df.columns

Index(['home_team', 'away_team', 'home_score', 'home_xg', 'home_penalty',
       'away_score', 'away_xg', 'away_penalty', 'home_manager', 'home_captain',
       'away_manager', 'away_captain', 'Attendance', 'Venue', 'Officials',
       'Round', 'Date', 'Score', 'Referee', 'Notes', 'Host', 'Year',
       'home_goal', 'away_goal', 'home_goal_long', 'away_goal_long',
       'home_own_goal', 'away_own_goal', 'home_penalty_goal',
       'away_penalty_goal', 'home_penalty_miss_long', 'away_penalty_miss_long',
       'home_penalty_shootout_goal_long', 'away_penalty_shootout_goal_long',
       'home_penalty_shootout_miss_long', 'away_penalty_shootout_miss_long',
       'home_red_card', 'away_red_card', 'home_yellow_red_card',
       'away_yellow_red_card', 'home_yellow_card_long',
       'away_yellow_card_long', 'home_substitute_in_long',
       'away_substitute_in_long'],
      dtype='object')

In [5]:
df.describe()

,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,Attendance,Year
count,964.000000,128.000000,35.000000,964.000000,128.000000,35.000000,964.000000,964.000000
mean,1.776971,1.435938,3.285714,1.044606,1.192187,3.057143,45693.374481,1989.244813
std,1.596676,0.860391,1.226459,1.071233,0.809258,1.136115,22704.131689,24.014409
min,0.000000,0.100000,0.000000,0.000000,0.000000,0.000000,2000.000000,1930.000000
25%,1.000000,0.800000,3.000000,0.000000,0.600000,2.000000,31800.000000,1974.000000
50%,1.000000,1.300000,3.000000,1.000000,1.000000,3.000000,42725.000000,1994.000000
75%,3.000000,1.925000,4.000000,2.000000,1.525000,4.000000,60984.500000,2010.000000
max,10.000000,5.200000,5.000000,7.000000,5.700000,5.000000,173850.000000,2022.000000

In [6]:
df.shape

(964, 44)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    object
 1   away_team                        964 non-null    object
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    object
 9   home_captain                     644 non-null    object
 10  away_manager                     964 non-null    object
 11  away_captain                     644 non-null    object
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    object
 14  Officials                        709 non-null    object
 15  Round                            964 non-null    object
 16  Date                             964 non-null    object
 17  Score                            964 non-null    object
 18  Referee                          709 non-null    object
 19  Notes                            73 non-null     object
 20  Host                             964 non-null    object
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    object
 23  away_goal                        571 non-null    object
 24  home_goal_long                   718 non-null    object
 25  away_goal_long                   571 non-null    object
 26  home_own_goal                    39 non-null     object
 27  away_own_goal                    17 non-null     object
 28  home_penalty_goal                116 non-null    object
 29  away_penalty_goal                84 non-null     object
 30  home_penalty_miss_long           6 non-null      object
 31  away_penalty_miss_long           9 non-null      object
 32  home_penalty_shootout_goal_long  34 non-null     object
 33  away_penalty_shootout_goal_long  34 non-null     object
 34  home_penalty_shootout_miss_long  24 non-null     object
 35  away_penalty_shootout_miss_long  30 non-null     object
 36  home_red_card                    51 non-null     object
 37  away_red_card                    54 non-null     object
 38  home_yellow_red_card             23 non-null     object
 39  away_yellow_red_card             31 non-null     object
 40  home_yellow_card_long            621 non-null    object
 41  away_yellow_card_long            627 non-null    object
 42  home_substitute_in_long          740 non-null    object
 43  away_substitute_in_long          747 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 331.5+ KB

In [ ]:
# Checking for any duplicates
df.duplicated().sum()

np.int64(0)